#cloud-config

apt_update: true

packages:
 - gzip
 - git
 - curl
 - python
 - libssl-dev
 - pkg-config
 - build-essential

runcmd:
 - curl -sL https://deb.nodesource.com/setup_4.x | bash -
 - apt-get install -y nodejs
 - git clone git://github.com/ether/etherpad-lite.git
 - cd etherpad-lite && bin/run.sh --root &
